// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace FinTrack.Backend.IntegrationTests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class DashboardFinanceiroFeature : object, Xunit.IClassFixture<DashboardFinanceiroFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Features", "Dashboard Financeiro", ("  Como um usuário do sistema FinTrack\r\n  Eu quero visualizar meu resumo financeir" +
                "o\r\n  Para ter controle sobre minhas finanças"), global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
        public DashboardFinanceiroFeature(DashboardFinanceiroFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
            await testRunner.GivenAsync("que eu sou o usuário \"11111111-1111-1111-1111-111111111111\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Visualizar dashboard sem transações")]
        [Xunit.TraitAttribute("FeatureTitle", "Dashboard Financeiro")]
        [Xunit.TraitAttribute("Description", "Visualizar dashboard sem transações")]
        public async System.Threading.Tasks.Task VisualizarDashboardSemTransacoes()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Visualizar dashboard sem transações", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.WhenAsync("eu consulto o dashboard", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.ThenAsync("a requisição deve ser bem-sucedida", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
                await testRunner.AndAsync("o total de receitas deve ser 0.00", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.AndAsync("o total de despesas deve ser 0.00", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.AndAsync("o balanço deve ser 0.00", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Visualizar dashboard com transações")]
        [Xunit.TraitAttribute("FeatureTitle", "Dashboard Financeiro")]
        [Xunit.TraitAttribute("Description", "Visualizar dashboard com transações")]
        public async System.Threading.Tasks.Task VisualizarDashboardComTransacoes()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Visualizar dashboard com transações", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Tipo",
                            "Categoria",
                            "Valor",
                            "Data",
                            "Descrição"});
                table1.AddRow(new string[] {
                            "Income",
                            "Salary",
                            "5000",
                            "2026-05-01",
                            "Salário Janeiro"});
                table1.AddRow(new string[] {
                            "Expense",
                            "Bills",
                            "1500",
                            "2026-05-05",
                            "Aluguel"});
                table1.AddRow(new string[] {
                            "Expense",
                            "Bills",
                            "500",
                            "2026-05-10",
                            "Conta de Luz"});
                await testRunner.GivenAsync("que existem as seguintes transações:", ((string)(null)), table1, "Dado ");
                await testRunner.WhenAsync("eu consulto o dashboard", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.ThenAsync("a requisição deve ser bem-sucedida", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
                await testRunner.AndAsync("o total de receitas deve ser 5000", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.AndAsync("o total de despesas deve ser 2000", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.AndAsync("o balanço deve ser 3000", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Dashboard com transações excluídas não deve contabilizá-las")]
        [Xunit.TraitAttribute("FeatureTitle", "Dashboard Financeiro")]
        [Xunit.TraitAttribute("Description", "Dashboard com transações excluídas não deve contabilizá-las")]
        public async System.Threading.Tasks.Task DashboardComTransacoesExcluidasNaoDeveContabiliza_Las()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Dashboard com transações excluídas não deve contabilizá-las", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "Tipo",
                            "Categoria",
                            "Valor",
                            "Data",
                            "Descrição"});
                table2.AddRow(new string[] {
                            "Income",
                            "Salary",
                            "3000",
                            "2026-05-01",
                            "Salário"});
                table2.AddRow(new string[] {
                            "Expense",
                            "Bills",
                            "1000",
                            "2026-05-05",
                            "Despesa 1"});
                await testRunner.GivenAsync("que existem as seguintes transações:", ((string)(null)), table2, "Dado ");
                await testRunner.AndAsync("a transação \"Despesa 1\" foi excluída", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.WhenAsync("eu consulto o dashboard", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.ThenAsync("a requisição deve ser bem-sucedida", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
                await testRunner.AndAsync("o total de receitas deve ser 3000", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.AndAsync("o total de despesas deve ser 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.AndAsync("o balanço deve ser 3000", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await DashboardFinanceiroFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await DashboardFinanceiroFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
