// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace FinTrack.Backend.IntegrationTests.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class GerenciamentoDeTransacoesFeature : object, Xunit.IClassFixture<GerenciamentoDeTransacoesFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Features", "Gerenciamento de Transações", ("  Como um usuário do sistema FinTrack\r\n  Eu quero gerenciar minhas transações fin" +
                "anceiras\r\n  Para manter meu histórico financeiro organizado"), global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
        public GerenciamentoDeTransacoesFeature(GerenciamentoDeTransacoesFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
            await testRunner.GivenAsync("que eu sou o usuário \"11111111-1111-1111-1111-111111111111\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Criar uma transação de receita")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Transações")]
        [Xunit.TraitAttribute("Description", "Criar uma transação de receita")]
        public async System.Threading.Tasks.Task CriarUmaTransacaoDeReceita()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Criar uma transação de receita", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table3.AddRow(new string[] {
                            "Tipo",
                            "Income"});
                table3.AddRow(new string[] {
                            "Categoria",
                            "22222222-2222-2222-2222-222222222221"});
                table3.AddRow(new string[] {
                            "Valor",
                            "5000.00"});
                table3.AddRow(new string[] {
                            "Data",
                            "2026-01-15"});
                table3.AddRow(new string[] {
                            "Descrição",
                            "Salário de Janeiro"});
                await testRunner.WhenAsync("eu crio uma transação com os seguintes dados:", ((string)(null)), table3, "Quando ");
                await testRunner.ThenAsync("a transação deve ser criada com sucesso", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
                await testRunner.AndAsync("a resposta deve conter o ID da transação", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.AndAsync("o tipo deve ser \"Income\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.AndAsync("o valor deve ser 5000.00", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Criar uma transação de despesa")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Transações")]
        [Xunit.TraitAttribute("Description", "Criar uma transação de despesa")]
        public async System.Threading.Tasks.Task CriarUmaTransacaoDeDespesa()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Criar uma transação de despesa", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "Campo",
                            "Valor"});
                table4.AddRow(new string[] {
                            "Tipo",
                            "Expense"});
                table4.AddRow(new string[] {
                            "Categoria",
                            "22222222-2222-2222-2222-222222222222"});
                table4.AddRow(new string[] {
                            "Valor",
                            "1200.00"});
                table4.AddRow(new string[] {
                            "Data",
                            "2026-01-20"});
                table4.AddRow(new string[] {
                            "Descrição",
                            "Aluguel"});
                await testRunner.WhenAsync("eu crio uma transação com os seguintes dados:", ((string)(null)), table4, "Quando ");
                await testRunner.ThenAsync("a transação deve ser criada com sucesso", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
                await testRunner.AndAsync("um registro de histórico deve ser criado com ação \"Created\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Atualizar uma transação existente")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Transações")]
        [Xunit.TraitAttribute("Description", "Atualizar uma transação existente")]
        public async System.Threading.Tasks.Task AtualizarUmaTransacaoExistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Atualizar uma transação existente", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync(("que existe uma transação de despesa no valor de 1000.00 com descrição \"Despesa Or" +
                        "iginal\""), ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("eu atualizo o valor para 1500.00", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.AndAsync("eu atualizo a descrição para \"Aluguel Atualizado\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.ThenAsync("a transação deve ser atualizada com sucesso", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
                await testRunner.AndAsync("o valor deve ser 1500.00", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.AndAsync("a descrição deve ser \"Aluguel Atualizado\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Excluir uma transação")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Transações")]
        [Xunit.TraitAttribute("Description", "Excluir uma transação")]
        public async System.Threading.Tasks.Task ExcluirUmaTransacao()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Excluir uma transação", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("que existe uma transação com descrição \"Despesa Temporária\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("eu excluo a transação", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.ThenAsync("a transação deve ser excluída com sucesso", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
                await testRunner.AndAsync("a transação não deve aparecer na listagem de transações", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Listar todas as transações do usuário")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Transações")]
        [Xunit.TraitAttribute("Description", "Listar todas as transações do usuário")]
        public async System.Threading.Tasks.Task ListarTodasAsTransacoesDoUsuario()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Listar todas as transações do usuário", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "Tipo",
                            "Valor",
                            "Descrição"});
                table5.AddRow(new string[] {
                            "Income",
                            "3000",
                            "Salário"});
                table5.AddRow(new string[] {
                            "Expense",
                            "500",
                            "Supermercado"});
                table5.AddRow(new string[] {
                            "Expense",
                            "200",
                            "Transporte"});
                await testRunner.GivenAsync("que existem as seguintes transações:", ((string)(null)), table5, "Dado ");
                await testRunner.WhenAsync("eu listo todas as transações", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.ThenAsync("devo ver 3 transações na lista", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
                await testRunner.AndAsync("a transação \"Salário\" deve estar na lista", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.AndAsync("a transação \"Supermercado\" deve estar na lista", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Buscar transação por ID")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Transações")]
        [Xunit.TraitAttribute("Description", "Buscar transação por ID")]
        public async System.Threading.Tasks.Task BuscarTransacaoPorID()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Buscar transação por ID", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("que existe uma transação com descrição \"Minha Transação\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.WhenAsync("eu busco a transação pelo ID", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.ThenAsync("a transação deve ser retornada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
                await testRunner.AndAsync("a descrição deve ser \"Minha Transação\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Consultar histórico de alterações de uma transação")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Transações")]
        [Xunit.TraitAttribute("Description", "Consultar histórico de alterações de uma transação")]
        public async System.Threading.Tasks.Task ConsultarHistoricoDeAlteracoesDeUmaTransacao()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Consultar histórico de alterações de uma transação", null, tagsOfScenario, argumentsOfScenario, featureTags);
            this.ScenarioInitialize(scenarioInfo);
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
                await this.FeatureBackgroundAsync();
                await testRunner.GivenAsync("que existe uma transação com descrição \"Transação Original\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
                await testRunner.AndAsync("a transação foi atualizada com descrição \"Transação Modificada 1\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.AndAsync("a transação foi atualizada com descrição \"Transação Modificada 2\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.WhenAsync("eu consulto o histórico da transação", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
                await testRunner.ThenAsync("devo ver 3 registros de histórico", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
                await testRunner.AndAsync("o primeiro registro deve ter ação \"Created\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
                await testRunner.AndAsync("os próximos 2 registros devem ter ação \"Updated\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await GerenciamentoDeTransacoesFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await GerenciamentoDeTransacoesFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
